const LOCAL_STORAGE_MAIN_KEY = '@go-swim:'

const LOCAL_STORAGE_CURRENT_TIMER_KEY = `${LOCAL_STORAGE_MAIN_KEY}current-time`
const LOCAL_STORAGE_CURRENT_SPRINTS_KEY = `${LOCAL_STORAGE_MAIN_KEY}current-sprints`

export {
  LOCAL_STORAGE_CURRENT_TIMER_KEY,
  LOCAL_STORAGE_CURRENT_SPRINTS_KEY
}